# Generated by Django 6.1 on 2026-08-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurator', '0001_initial'),
        ('inventory', '0002_product_kind_stockmovement_reason_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations', to='purchases.purchase'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configurator.configuration'),
        ),
    ]
