# Generated by Django 6.1 on 2026-08-27 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_initial'),
        ('inventory', '0003_product_base_model_product_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_configurations', to='inventory.product'),
        ),
    ]
