# Generated by Django 6.1 on 2026-08-27 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_configuration_variant'),
        ('inventory', '0004_remove_product_category_remove_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='mode',
            field=models.CharField(choices=[('build', "Butlovchilardan yig'ish"), ('modify', "Tayyor mahsulotni o'zgartirish")], default='build', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfigurationRemoval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_removals', to='inventory.product')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removals', to='configurator.configuration')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
