# Generated by Django 6.1 on 2026-08-27 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0005_configurationrequest'),
        ('inventory', '0004_remove_product_category_remove_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationrequest',
            name='base_product',
            field=models.ForeignKey(blank=True, help_text="Sales taxmin qilgan bazaviy model — take'da shu bo'yicha konfiguratsiya ochiladi", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_requests', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='configurationrequest',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_requests', to='inventory.warehouse'),
        ),
    ]
