# Generated by Django 6.1 on 2026-09-01 22:47

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_configurationrequest_base_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='acts/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx', 'xls', 'xlsx'], message='Bu fayl turi qabul qilinmaydi. Ruxsat: pdf, rasm (jpg/png/webp), doc(x), xls(x).'), apps.core.validators.validate_upload_size]),
        ),
    ]
