# Generated by Django 6.1 on 2026-09-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0007_alter_act_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='purchase',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='status',
            field=models.CharField(choices=[('draft', 'Chernovik'), ('ready', 'Tayyor'), ('sold', 'Sotildi'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='configurationrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Engineer ishlamoqda'), ('done', 'Konfiguratsiya tayyor'), ('archived', 'Arxivlangan'), ('cancelled', 'Bekor qilingan')], default='new', max_length=20),
        ),
    ]
