# Generated by Django 6.1 on 2026-09-16 08:00

from django.db import migrations, models
from django.db.models import F


def fill_from_created_at(apps, schema_editor):
    for model_name in ('Configuration', 'ConfigurationRequest'):
        apps.get_model('configurator', model_name).objects.filter(
            status_changed_at__isnull=True,
        ).update(status_changed_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0008_remove_configuration_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configurationrequest',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(fill_from_created_at, migrations.RunPython.noop),
    ]
