# Generated by Django 6.1 on 2026-09-16 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0009_configuration_status_changed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='assembled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='status',
            field=models.CharField(choices=[('draft', 'Chernovik'), ('pending_sales', "Sales ko'rigida"), ('approved', 'Texnik yechim tasdiqlandi'), ('ready', 'Tayyor'), ('sold', 'Sotildi'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfigurationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.CharField(choices=[('sales', 'Sales — texnik yechim')], default='sales', max_length=20)),
                ('decision', models.CharField(choices=[('approved', 'Tasdiqlandi'), ('rejected', 'Qaytarildi')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='configurator.configuration')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
