# Generated by Django 6.1 on 2026-09-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0010_configuration_assembled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configurationrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
