# Generated by Django 6.1 on 2026-09-18 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0011_configuration_quantity_configurationrequest_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Engineer ishlamoqda'), ('returned', "Sales'ga qaytarildi"), ('done', 'Konfiguratsiya tayyor'), ('archived', 'Arxivlangan'), ('cancelled', 'Bekor qilingan')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfigurationRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('created', 'Zayavka yozildi'), ('taken', 'Engineer ishga oldi'), ('returned', "Engineer qaytardi (sales'ga)"), ('resent', 'Sales tuzatib qayta yubordi'), ('price_asked', "Narx so'raldi (buyurtmachiga)"), ('price_given', 'Narx kiritildi'), ('cancelled', 'Zanjir bekor qilindi'), ('note', 'Izoh')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_request_events', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='configurator.configurationrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
