# Generated by Django 6.1 on 2026-09-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0012_alter_configurationrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
    ]
