# Generated by Django 6.1 on 2026-09-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0013_configuration_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='status',
            field=models.CharField(choices=[('draft', 'Chernovik'), ('pending_clarification', "Sales'dan javob kutilmoqda"), ('pending_sales', "Sales ko'rigida"), ('approved', 'Texnik yechim tasdiqlandi'), ('ready', 'Tayyor'), ('sold', 'Sotildi'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='configurationapproval',
            name='decision',
            field=models.CharField(choices=[('approved', 'Tasdiqlandi'), ('rejected', 'Qaytarildi'), ('question', "So'rov"), ('answer', 'Javob')], max_length=20),
        ),
        migrations.AlterField(
            model_name='configurationapproval',
            name='step',
            field=models.CharField(choices=[('sales', 'Sales — texnik yechim'), ('engineer', 'Engineer savoli')], default='sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='configurationrequestevent',
            name='stage',
            field=models.CharField(choices=[('created', 'Zayavka yozildi'), ('taken', 'Engineer ishga oldi'), ('returned', "Engineer qaytardi (sales'ga)"), ('released', 'Engineer ishni qaytardi (hovuzga)'), ('resent', 'Sales tuzatib qayta yubordi'), ('price_asked', "Narx so'raldi (buyurtmachiga)"), ('price_given', 'Narx kiritildi'), ('cancelled', 'Zanjir bekor qilindi'), ('note', 'Izoh')], max_length=20),
        ),
    ]
