# Generated by Django 6.1 on 2026-09-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0014_alter_configuration_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationapproval',
            options={'ordering': ['created_at']},
        ),
    ]
