# Generated by Django 6.1 on 2026-09-22 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0015_alter_configurationapproval_options'),
        ('inventory', '0005_stockreservation'),
        ('sales', '0010_contract_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('model', "Model (yig'iladigan)"), ('item', 'Tovar (tayyor, konfiguratorsiz)')], default='model', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('text', models.TextField(blank=True, help_text='Shu qatorga tegishli izoh')),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.product')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_request_lines', to='configurator.configuration')),
                ('contract_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales.contractitem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='configurator.configurationrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
