# Generated by Django 6.1 on 2026-09-24 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0016_configuration_request_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('pending_bugalter', "Bugalter tasdig'i kutilmoqda"), ('approved', 'Tasdiqlandi'), ('rejected', 'Qaytarildi')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='act',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('approved', 'Tasdiqlandi'), ('rejected', 'Qaytarildi')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='configurator.act')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='act_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
