# Generated by Django 6.1 on 2026-09-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0017_act_status_act_status_changed_at_actapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationrequestevent',
            name='stage',
            field=models.CharField(choices=[('created', 'Zayavka yozildi'), ('taken', 'Engineer ishga oldi'), ('returned', "Engineer qaytardi (sales'ga)"), ('released', 'Engineer ishni qaytardi (hovuzga)'), ('resent', 'Sales tuzatib qayta yubordi'), ('price_asked', "Narx so'raldi (buyurtmachiga)"), ('price_given', 'Narx kiritildi'), ('logistics_asked', "Logistika narxi so'raldi"), ('logistics_given', 'Logistika narxi keldi'), ('customs_given', 'Bojxona hisobi keldi'), ('cancelled', 'Zanjir bekor qilindi'), ('note', 'Izoh')], max_length=20),
        ),
    ]
