# Generated by Django 6.1 on 2026-09-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0018_alter_configurationrequestevent_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='mode',
            field=models.CharField(choices=[('build', "Butlovchilardan yig'ish"), ('modify', "Tayyor mahsulotni o'zgartirish"), ('order', 'Butun model sifatida buyurtma')], default='build', max_length=20),
        ),
    ]
