# Generated by Django 6.1 on 2026-09-11 11:50

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=apps.core.utils.default_vat_percent, max_digits=5, verbose_name='QQS %'),
        ),
    ]
