# Generated by Django 6.1 on 2026-09-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_contractitem_vat_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='didox_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='didox_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Didox raqami'),
        ),
    ]
