# Generated by Django 6.1 on 2026-09-16 08:00

from django.db import migrations, models
from django.db.models import F


def fill_from_created_at(apps, schema_editor):
    """Eski yozuvlarga boshlang'ich qiymat — yaratilgan vaqti."""
    apps.get_model('sales', 'Contract').objects.filter(
        status_changed_at__isnull=True,
    ).update(status_changed_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_contract_didox_accepted_at_contract_didox_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(fill_from_created_at, migrations.RunPython.noop),
    ]
