# Generated by Django 6.1 on 2026-09-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_contract_status_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='delivered_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
