# Generated by Django 6.1 on 2026-09-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_contract_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='didox_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('pending_bugalter', "Bugalter tasdig'i kutilmoqda"), ('pending_didox', "Didox tasdig'i kutilmoqda"), ('pending_admin', "Admin tasdig'i kutilmoqda"), ('approved', 'Tasdiqlandi, pul kutilmoqda'), ('active', 'Pul keldi, muddat ketmoqda'), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='contractapproval',
            name='step',
            field=models.CharField(choices=[('bugalter', 'Bugalter'), ('didox', 'Didox'), ('admin', 'Admin'), ('payment', "To'lov tasdig'i")], max_length=20),
        ),
    ]
