# Generated by Django 6.1 on 2026-09-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_contract_delivered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('pending_bugalter', "Bugalter tasdig'i kutilmoqda"), ('pending_admin', "Admin tasdig'i kutilmoqda"), ('ready_for_didox', 'Didoxga yuborilishi kerak'), ('pending_didox', "Didox tasdig'i kutilmoqda"), ('approved', 'Tasdiqlandi, pul kutilmoqda'), ('active', 'Pul keldi, muddat ketmoqda'), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=30),
        ),
    ]
