# Generated by Django 6.1 on 2026-09-21 20:28

import django.db.models.deletion
from django.db import migrations, models


def backfill_item_configuration(apps, schema_editor):
    """12-§2 (C1): mavjud qatorlarga `contract.configuration` dan to'ldiriladi.

    Bu paytda har bir shartnomada faqat BITTA model bor edi (yangi ko'p
    modelli imkoniyat shu migratsiyadan keyin ochiladi) — shuning uchun
    to'g'ridan-to'g'ri `contract.configuration_id` yetarli.
    """
    Contract = apps.get_model('sales', 'Contract')
    for contract in Contract.objects.filter(configuration__isnull=False):
        contract.items.filter(configuration__isnull=True).update(
            configuration_id=contract.configuration_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0015_alter_configurationapproval_options'),
        ('sales', '0008_contract_ready_for_didox'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractitem',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_items', to='configurator.configuration'),
        ),
        migrations.RunPython(backfill_item_configuration, migrations.RunPython.noop),
    ]
