# Generated by Django 6.1 on 2026-09-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_contract_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdocument',
            name='source_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
