# Generated by Django 6.1 on 2026-09-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_contractdocument_source_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdocument',
            name='docx_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='wopi_lock',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='wopi_lock_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
