# Generated by Django 6.1 on 2026-09-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_contractdocument_docx_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdocument',
            name='rendered_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
