# Generated by Django 6.1 on 2026-09-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_contractdocument_rendered_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractapproval',
            name='returned_to',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
