# Generated by Django 6.1 on 2026-09-25 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_contractapproval_returned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractdocument',
            name='docx_version',
        ),
        migrations.RemoveField(
            model_name='contractdocument',
            name='rendered_total',
        ),
        migrations.RemoveField(
            model_name='contractdocument',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='contractdocument',
            name='source_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='contractdocument',
            name='wopi_lock',
        ),
        migrations.RemoveField(
            model_name='contractdocument',
            name='wopi_lock_expires_at',
        ),
        migrations.AddField(
            model_name='contract',
            name='delivery_days',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='has_requisites',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='has_specification',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(default='ru', max_length=5)),
                ('body', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('has_specification', models.BooleanField(default=True)),
                ('has_requisites', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sales.contracttemplate'),
        ),
    ]
