# Generated by Django 6.1 on 2026-09-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_remove_contractdocument_docx_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='prepayment_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
