# Generated by Django 6.1 on 2026-08-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('bugalter', 'Bugalter'), ('sales', 'Sales')], default='sales', max_length=20),
        ),
    ]
