# Generated by Django 6.1 on 2026-08-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('bugalter', 'Bugalter'), ('sales', 'Sales'), ('buyurtmachi', 'Buyurtmachi')], default='sales', max_length=20),
        ),
    ]
