# Generated by Django 6.1 on 2026-09-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('bugalter', 'Bugalter'), ('sales', 'Sales'), ('buyurtmachi', 'Buyurtmachi'), ('engineer', 'Engineer'), ('logist', 'Logist'), ('deklarant', 'Deklarant')], default='sales', max_length=20),
        ),
    ]
