# Generated by Django 6.1 on 2026-08-27 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_loan_source'),
        ('inventory', '0003_product_base_model_product_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Replenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=30, unique=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('pending_bugalter', 'Bugalter tekshiruvida'), ('pending_admin', 'Admin tasdiqlashida'), ('approved', 'Tasdiqlandi, buyurtma berish mumkin'), ('ordered', 'Buyurtma berildi'), ('in_transit', "Yo'lda"), ('customs', 'Bojxonada'), ('delivered', 'Omborga kirim qilindi'), ('rejected', 'Rad etildi'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=30)),
                ('currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'AQSH dollari'), ('EUR', 'Yevro'), ('CNY', 'Yuan')], default='UZS', max_length=3)),
                ('logistics_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('expected_at', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishments', to=settings.AUTH_USER_MODEL)),
                ('debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishments', to='finance.loan')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishments', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.CharField(choices=[('bugalter', 'Bugalter tekshiruvi'), ('admin', 'Admin tasdig’i')], max_length=20)),
                ('decision', models.CharField(choices=[('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_approvals', to=settings.AUTH_USER_MODEL)),
                ('replenishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='procurement.replenishment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('ordered', 'Buyurtma berildi'), ('shipped', 'Jo’natildi'), ('customs', 'Bojxonada'), ('cleared', 'Bojxonadan chiqdi'), ('arrived', 'Yetib keldi'), ('note', 'Izoh')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('happened_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_events', to=settings.AUTH_USER_MODEL)),
                ('replenishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='procurement.replenishment')),
            ],
            options={
                'ordering': ['happened_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_items', to='inventory.product')),
                ('replenishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.replenishment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
