# Generated by Django 6.1 on 2026-08-28 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_configurationrequest_base_product_and_more'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishment',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishments', to='configurator.configuration'),
        ),
    ]
