# Generated by Django 6.1 on 2026-09-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_replenishment_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishmentitem',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='QQS %'),
        ),
    ]
