# Generated by Django 6.1 on 2026-09-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_replenishmentitem_vat_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replenishment',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('pending_sales', 'Sales — mijoz roziligi kutilmoqda'), ('pending_bugalter', 'Bugalter tekshiruvida'), ('pending_admin', 'Admin tasdiqlashida'), ('approved', 'Tasdiqlandi, buyurtma berish mumkin'), ('ordered', 'Buyurtma berildi'), ('in_transit', "Yo'lda"), ('customs', 'Bojxonada'), ('delivered', 'Omborga kirim qilindi'), ('rejected', 'Rad etildi'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='replenishmentapproval',
            name='step',
            field=models.CharField(choices=[('sales', 'Sales — mijoz roziligi'), ('bugalter', 'Bugalter tekshiruvi'), ('admin', 'Admin tasdig’i')], max_length=20),
        ),
    ]
