# Generated by Django 6.1 on 2026-09-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_alter_replenishment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishment',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='replenishment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=18),
        ),
    ]
