# Generated by Django 6.1 on 2026-09-16 08:00

from django.db import migrations, models
from django.db.models import F


def fill_from_created_at(apps, schema_editor):
    apps.get_model('procurement', 'Replenishment').objects.filter(
        status_changed_at__isnull=True,
    ).update(status_changed_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_replenishment_owner_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishment',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(fill_from_created_at, migrations.RunPython.noop),
    ]
