# Generated by Django 6.1 on 2026-09-16 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_replenishment_status_changed_at'),
        ('sales', '0005_contract_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishments', to='sales.contract'),
        ),
    ]
