# Generated by Django 6.1 on 2026-09-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0016_configuration_request_line'),
        ('procurement', '0008_replenishment_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='replenishmentitem',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_items', to='configurator.configuration'),
        ),
    ]
