# Generated by Django 6.1 on 2026-09-27 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0017_act_status_act_status_changed_at_actapproval'),
        ('inventory', '0008_product_is_imported_product_tnved_code'),
        ('procurement', '0009_replenishment_item_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Chernovik'), ('waiting_logistics', 'Logist kutilmoqda'), ('waiting_customs', 'Deklarant kutilmoqda'), ('done', 'Tannarx chiqdi'), ('cancelled', 'Bekor qilindi')], default='draft', max_length=20)),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=18)),
                ('vat_recoverable', models.BooleanField(default=False)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('goods_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('goods_filled_at', models.DateTimeField(blank=True, null=True)),
                ('logistics_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('logistics_note', models.TextField(blank=True)),
                ('logistics_filled_at', models.DateTimeField(blank=True, null=True)),
                ('tnved_code', models.CharField(blank=True, max_length=20)),
                ('freight_to_border', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('duty_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('duty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('excise_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('customs_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('certificate_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('laboratory_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('declarant_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('customs_note', models.TextField(blank=True)),
                ('customs_filled_at', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sheets', to='configurator.configuration')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customs_filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('goods_filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('logistics_filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_sheets', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
