# Generated by Django 6.1 on 2026-09-30 04:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0019_alter_configuration_mode'),
        ('inventory', '0009_price_request_and_product_customs_cache'),
        ('procurement', '0010_importcostsheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting_logistics', 'Logist kutilmoqda'), ('waiting_customs', 'Deklarant kutilmoqda'), ('waiting_supplier', 'Buyurtmachi kutilmoqda'), ('answered', 'Narx berildi'), ('cancelled', 'Bekor qilindi')], default='waiting_supplier', max_length=20)),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_requests', to='configurator.configuration')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=18)),
                ('is_imported', models.BooleanField(default=False)),
                ('vat_recoverable', models.BooleanField(default=False)),
                ('logistics_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('freight_to_border', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('logistics_note', models.TextField(blank=True)),
                ('logistics_filled_at', models.DateTimeField(blank=True, null=True)),
                ('tnved_code', models.CharField(blank=True, max_length=20, verbose_name='TN VED')),
                ('duty_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('duty_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('excise_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('customs_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('certificate_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('laboratory_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('declarant_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('customs_note', models.TextField(blank=True)),
                ('customs_filled_at', models.DateTimeField(blank=True, null=True)),
                ('customs_auto_filled', models.BooleanField(default=False)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('goods_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_request_lines', to='inventory.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.pricerequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
