# Generated by Django 6.1 on 2026-09-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_price_request_and_product_customs_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerequestline',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
