# Generated by Django 6.1 on 2026-09-30 11:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_price_request_filled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerequestline',
            name='extra_costs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
    ]
