# Generated by Django 6.1 on 2026-08-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='source',
            field=models.CharField(choices=[('personal', 'Shaxsiy qarz'), ('supplier', "Ta'minotchi oldidagi qarz")], default='personal', max_length=20),
        ),
    ]
