# Generated by Django 6.1 on 2026-09-15 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_loan_source'),
        ('procurement', '0005_replenishment_debt_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='replenishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='procurement.replenishment'),
        ),
    ]
