# Generated by Django 6.1 on 2026-09-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='STIR / INN')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('mfo', models.CharField(blank=True, max_length=10)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('director_name', models.CharField(blank=True, max_length=200)),
                ('contract_terms', models.TextField(blank=True, help_text='Shartnoma chop etilganda chiqadigan standart shartlar matni')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
