# Generated by Django 6.1 on 2026-09-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='admin_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Shu summadan kichik shartnomalar admin tasdig'isiz o'tadi (QQS bilan, UZS); 0 — chegara yo'q", max_digits=18),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='configuration_reservation_days',
            field=models.PositiveIntegerField(default=14, help_text='Konfiguratsiya chernovigi rejadagi bronni necha kun ushlab turadi (0 — cheksiz)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contract_reservation_days',
            field=models.PositiveIntegerField(default=7, help_text='Shartnoma chernovigi bronni necha kun ushlab turadi (0 — cheksiz)'),
        ),
    ]
