# Generated by Django 6.1 on 2026-09-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_user_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='replenishment_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Shu summadan kichik to'ldirish hisoblari admin tasdig'isiz o'tadi (QQS+xarajatlar bilan, UZS); 0 — chegara yo'q", max_digits=18),
        ),
    ]
