# Generated by Django 6.1 on 2026-09-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companyprofile_replenishment_approval_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='sla_cutoff_hour',
            field=models.PositiveIntegerField(default=16, help_text='Kesim soati: shu soatdan keyin kelgan ish keyingi ish kunidan sanaladi'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='sla_working_days',
            field=models.PositiveIntegerField(default=1, help_text='Ishga beriladigan ish kunlari soni'),
        ),
    ]
