# Generated by Django 6.1 on 2026-09-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_companyprofile_sla_cutoff_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Sotuv narxi yo'q mahsulotda tannarx ustiga avtomatik ustama (%); 0 — ustama yo'q, tannarx ishlatiladi", max_digits=5),
        ),
    ]
