# Generated by Django 6.1 on 2026-09-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companyprofile_markup_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='city',
            field=models.CharField(blank=True, help_text='Masalan: "г. Ташкент" — shartnoma sarlavhasida', max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='director_title',
            field=models.CharField(blank=True, help_text='Masalan: "Генерального директора" — lavozim, shartnoma sarlavhasida', max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='license',
            field=models.CharField(blank=True, help_text='Litsenziya raqami va kim bergani', max_length=300),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='oked',
            field=models.CharField(blank=True, max_length=20, verbose_name='ОКЭД'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='registration_code',
            field=models.CharField(blank=True, max_length=50, verbose_name="Ro'yxatga olish kodi"),
        ),
    ]
