# Generated by Django 6.1 on 2026-09-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companyprofile_city_companyprofile_director_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='default_customs_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Bojxona yig'imi uchun taklif qilinadigan summa (deklarant o'zgartira oladi)", max_digits=18),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vat_recoverable',
            field=models.BooleanField(default=False, help_text="Import QQS si hisobga olinadimi (olinsa tannarxga QO'SHILMAYDI)"),
        ),
    ]
