# Generated by Django 6.1 on 2026-09-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_companyprofile_default_customs_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='min_margin_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shartnomada tannarx ustiga eng kam ustama (%). Bundan past narx sariq, tannarxdan past yoki teng narx qizil ogohlantirish beradi. 0 — faqat tannarxdan past holat tekshiriladi', max_digits=5),
        ),
    ]
