# Generated by Django 6.1 on 2026-08-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('machine', 'Tayyor model'), ('component', 'Butlovchi'), ('other', 'Boshqa')], default='machine', max_length=20),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Kirim hujjati'), ('sale', 'Sotuv'), ('configuration', 'Configurator'), ('manual', "Qo'lda")], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spec_usages', to='inventory.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='inventory.product')),
            ],
            options={
                'ordering': ['label', 'id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'component'), name='uniq_product_spec_component')],
            },
        ),
    ]
