# Generated by Django 6.1 on 2026-08-27 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_kind_stockmovement_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='signature',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
