# Generated by Django 6.1 on 2026-08-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_base_model_product_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
