# Generated by Django 6.1 on 2026-09-15 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0008_remove_configuration_purchase_and_more'),
        ('inventory', '0004_remove_product_category_remove_product_barcode_and_more'),
        ('sales', '0003_contract_didox_accepted_at_contract_didox_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('kind', models.CharField(choices=[('soft', 'Rejada'), ('hard', 'Band')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('released', "Bo'shatilgan"), ('shipped', 'Chiqim qilindi'), ('expired', 'Muddati tugadi')], default='active', max_length=20)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('release_note', models.TextField(blank=True)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='configurator.configuration')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='sales.contract')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.product')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_reservations', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.warehouse')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('configuration__isnull', True), ('contract__isnull', False)), models.Q(('configuration__isnull', False), ('contract__isnull', True)), _connector='OR'), name='reservation_exactly_one_owner')],
            },
        ),
    ]
