# Generated by Django 6.1 on 2026-09-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_deactivate_variant_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='dona', max_length=20),
        ),
    ]
