# Generated by Django 6.1 on 2026-09-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='tnved_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='TN VED'),
        ),
    ]
