# Generated by Django 6.1 on 2026-09-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_is_imported_product_tnved_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='product',
            name='duty_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='laboratory_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
