# Generated by Django 6.1 on 2026-09-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_account_number_client_bank_name_client_mfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='director_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
