# Generated by Django 6.1 on 2026-08-27 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('contract', 'Shartnoma'), ('invoice', 'Invoys (faktura)'), ('customs', 'Bojxona deklaratsiyasi'), ('other', 'Boshqa hujjat')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='purchase-documents/')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='purchases.purchase')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
