# Generated by Django 6.1 on 2026-09-01 22:47

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchasedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedocument',
            name='file',
            field=models.FileField(upload_to='purchase-documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp', 'doc', 'docx', 'xls', 'xlsx'], message='Bu fayl turi qabul qilinmaydi. Ruxsat: pdf, rasm (jpg/png/webp), doc(x), xls(x).'), apps.core.validators.validate_upload_size]),
        ),
    ]
